version: '3.9'

volumes:
  pg_url:
  pgadmin_data:

services:
  url_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123qweASD
      - POSTGRES_DB=url_db
    volumes:
      - pg_url:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
    - pgadmin_data:/var/lib/pgadmin

  java_app:
    container_name: java_app
    image: app:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://url_db:5432/url_db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=123qweASD
    depends_on:
    - url_db
    